spring:
    application:
        name: readiness-liveness-probe

management:
    endpoint:
        health:
            probes:
                enabled: true
    endpoints:
        web:
            exposure:
                include: health,info
    health:
        livenessState:
            enabled: true
        readinessState:
            enabled: true
server:
    port: 8080
